config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :views
  root to: 'pages#home'

  resources :users, only: [:show, :update] do
    resources :projects, only: [:index]
  end

  resources :projects do
    resources :contributions, only: [:new, :create]
  end

  resources :knowledges, only: [:new, :create, :destroy]

  get 'contributions/:id/remove_user', to: "contributions#remove_user", as: "remove_contribution_user"

  resources :contributions, only: [:edit, :update, :destroy, :show] do
    resources :requirements, only: [:new, :create]
    resources :interests, only: [:create]
  end

  resources :interests, only: [:destroy]

  resources :requirements, only: [:destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <head>
    <!-- <link rel="stylesheet" type="text/css" href="style.css"> -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>


<!-- Footer -->
<footer class="page-footer font-small indigo mt-4">

  <!-- Footer Links -->
  <div class="container">

    <!-- Grid row-->
    <div class="row text-center d-flex justify-content-center pt-5 mb-3">
      <div class="col-md-1">

      </div>
      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">About us</a>
        </h6>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">Products</a>
        </h6>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">Awards</a>
        </h6>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">Help</a>
        </h6>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">Contact</a>
        </h6>
      </div>
      <!-- Grid column -->
      <div class="col-md-1">

      </div>
    </div>
    <!-- Grid row-->
    <hr class="rgba-white-light" style="margin: 1% 15%;">

    <!-- Grid row-->
    <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">

      <!-- Grid column -->
      <div class="col-md-8 col-md-offset-2 mt-5">
        <p style="line-height: 1.7rem">Open source software is free for you to use and explore. Get involved to perfect your craft and be part of something big. Stay connected with the community by signing up for our weekly newsletter. You can also find us on these sites:</p>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->
    <hr class="clearfix d-md-none rgba-white-light" style="margin: 0% 15% 1%;">

    <!-- Grid row-->
    <div class="row pb-3">

      <!-- Grid column -->
      <div class="col-md-12 text-center">

        <div class="mb-5 flex-center">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fa fa-facebook fa-lg white-text mr-md-4"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fa fa-twitter fa-lg white-text mr-md-4"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fa fa-google-plus fa-lg white-text mr-md-4"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fa fa-linkedin fa-lg white-text mr-md-4"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fa fa-instagram fa-lg white-text mr-md-4"> </i>
          </a>
          <!--Pinterest-->
          <a class="pin-ic">
            <i class="fa fa-pinterest fa-lg white-text"> </i>
          </a>

        </div>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright: Git Legit
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Search Bar -->

  <%= form_tag projects_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control navbar",
      placeholder: "Search for projects..."
    %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if current_user %>
      <%= link_to "Add skill", new_knowledge_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "New project", new_project_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <% if current_user %>
        <div class="dropdown">
          <div class="user-image-navbar" data-toggle="dropdown">
            <% if current_user.photo.present? %>
              <% photo = cl_image_tag current_user.photo%>
            <% else %>
              <% photo = cl_image_tag('avatar.png') %>
            <% end %>
            <%= photo %>
          </div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      <% else %>
        <%= link_to "Log In", new_user_session_path, class: "navbar-wagon-link btn btn-primary btn-lg" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-link btn btn-primary btn-lg" %>
      <% end %>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <% if current_user %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
             <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>