config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :views
  root to: 'pages#home'

  resources :users, only: [:show, :update] do
    resources :projects, only: [:index]
  end

  resources :projects do
    resources :contributions, only: [:new, :create]
  end

  resources :knowledges, only: [:new, :create, :destroy]

  get 'contributions/:id/remove_user', to: "contributions#remove_user", as: "remove_contribution_user"

  resources :contributions, only: [:edit, :update, :destroy, :show] do
    resources :requirements, only: [:new, :create]
    resources :interests, only: [:create]
  end

  resources :interests, only: [:destroy]

  resources :requirements, only: [:destroy]
end

app/views/pages/_banner.html.erb
<div class="banner" style="background-image: url(<%= image_path('banner-new.jpg') %>)">
  <div class="banner-content">
    <h1>Git Legit</h1>
    <p>Find collaborators for your open-source project</p>
    <% if current_user %>
    <%= link_to "Create a Project", new_project_path, class: "bttn-dark car-position" %>
    <% else %>
    <%= link_to "Log In", new_user_session_path, class: "bttn-dark car-position" %>
    <% end %>
  </div>
</div>

app/views/pages/_how.html.erb
<div class="banner" style="background-image: url(<%= image_path('how.jpg') %>)">
  <div class="how-content">
    <h1>Open Source Is Supported By Everyone</h1>
    <p>This belief underlines the mission of the best OSS shops and developers. It pushes them to build new features and contribute these features back to the community. As a direct result, popular OSS projects are always on the cutting-edge of technology.</p>
  </div>
</div>

app/views/pages/_m.html.erb
<div class="banner-m" style="background-image: url(<%= image_path('m.jpg') %>)">
  <div class="how-content">
    <h1>What will you do?</h1>
    <p></p>
  </div>
</div>

app/views/pages/_results_home.html.erb
<% @projects.each_with_index do |project, i| %>
  <div class="col-xs-12 col-sm-4">
    <div class="thecard">
      <div class="card-img">
        <% if project.photo.present? %>
          <% photo = cl_image_tag project.photo%>
        <% else %>
          <% photo = cl_image_tag('logo.png') %>
        <% end %>
        <%= photo %>
      </div>
      <div class="card-caption">
        <i id="clock-btn" class="far fa-clock"></i>
        <span class="date">Last updated: <%= project.updated_at %></span>
        <h1 class="project-title"><%= project.title %></h1>
        <p class ="card-description"><%= project.description[0, 100] %></p>

        <div class="reqs-box">
          <p class ="card-skills"><strong><em>Relevant skills:</em> &ensp;</strong></p>
          <div class="reqs">
            <% project.skills.each do |skill| %>
              <i class="devicon-<%= skill.slug %>"></i>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card-out">
        <h5>Read more</h5>
        <i id="out-icon" class="fa fa-angle-right"></i>
      </div>
      <a class="card-link" href="<%= project_path(project) %>" ></a>
    </div>
  </div>
<% end %>

app/views/pages/_user_show_contributions_cards.html.erb
<div class="user-contributions section" id="last-section">
  <h3>Contributions you are working on:</h3>
  <div class="row">
    <% @user.contributions.each do |contribution| %>
    <div class="col-xs-12 col-sm-4">
      <div class="thecard">
        <div class="card-caption">
          <div class="card-delete">
            <% if contribution.user == current_user %>
              <%= link_to remove_contribution_user_path(contribution) do %>
                <p>unassign</p>
              <% end %>
            <% end %>
          </div>
          <i id="clock-btn" class="far fa-clock"></i>
          <span class="date">Last updated: <%= contribution.updated_at %></span>
          <h1 class="project-title"><%= contribution.title %></h1>
          <p class="card-description"><%= contribution.description[0, 100] %></p>
          <div class="reqs-box">
            <p class ="card-skills"><strong><em>Relevant skills:</em> &ensp;</strong></p>
            <div class="reqs">
              <% contribution.skills.each do |skill| %>
              <i class="devicon-<%= skill.slug %>"></i>
              <% end %>
            </div>
          </div>
        </div>
        <div class="card-out">
          <h5>Read more</h5>
          <i id="out-icon" class="fa fa-angle-right"></i>
        </div>
        <a class="card-link" href="<%= contribution_path(contribution) %>" ></a>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/pages/_user_show_interests_cards.html.erb
<div class="user-interests section">
  <h3>Contributions you are interested in:</h3>
  <div class="row">
    <% @user.interests.each do |interest| %>
    <div class="col-xs-12 col-sm-4">
      <div class="thecard">
        <div class="card-caption">
          <div class="card-delete">
            <% if interest.user == current_user %>
              <%= link_to interest_path(interest), method: :delete do %>
                <i class="far fa-trash-alt"></i>
              <% end %>
            <% end %>
          </div>
          <i id="clock-btn" class="far fa-clock"></i>
          <span class="date">Last updated: <%= interest.updated_at %></span>
          <h1 class="project-title"><%= interest.contribution.title %></h1>
          <p class="card-description"><%= interest.contribution.description[0, 100] %></p>
          <div class="reqs-box">
            <p class ="card-skills"><strong><em>Relevant skills:</em> &ensp;</strong></p>
            <div class="reqs">
              <% interest.contribution.skills.each do |skill| %>
              <i class="devicon-<%= skill.slug %>"></i>
              <% end %>
            </div>
          </div>
        </div>
        <div class="card-out">
          <h5>Read more</h5>
          <i id="out-icon" class="fa fa-angle-right"></i>
        </div>
        <a class="card-link" href="<%= contribution_path(interest.contribution) %>" ></a>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/pages/_user_show_projects_cards.html.erb
<div class="user-projects section">
  <h3>Projects:</h3>
  <div class="row">
    <% @user.projects.each do |project| %>
    <div class="col-xs-12 col-sm-4">
      <div class="thecard">
       <div class="card-img">
         <% if project.photo.present? %>
           <% photo = cl_image_tag project.photo%>
         <% else %>
           <% photo = cl_image_tag('logo.png') %>
         <% end %>
         <%= photo %>
       </div>
        <div class="card-caption">
          <div class="card-delete">
            <% if project.user == current_user %>
            <%= link_to project_path(project), method: :delete do %>
            <i class="far fa-trash-alt"></i>
            <% end %>
            <% end %>
          </div>
          <i id="clock-btn" class="far fa-clock"></i>
          <span class="date">Last updated: <%= project.updated_at %></span>
          <h1 class="project-title"><%= project.title %></h1>
          <p class="card-description"><p><%= project.description[0, 100] %></p>
          <div class="reqs-box">
            <p class ="card-skills"><strong><em>Relevant skills:</em> &ensp;</strong></p>
            <div class="reqs">
              <% project.skills.each do |skill| %>
              <i class="devicon-<%= skill.slug %>"></i>
              <% end %>
            </div>
          </div>
          <p class="green" id="bright"><%= "New interest" if project.interest? %></p>
        </div>
        <div class="card-out">
          <h5>Read more</h5>
          <i id="out-icon" class="fa fa-angle-right"></i>
        </div>
        <a class="card-link" href="<%= project_path(project) %>" ></a>
      </div>
    </div>
    <% end %>
  </div>
  <div class="new-project-button btn btn-primary">
    <%= link_to "Create a New Project", new_project_path, class: "btn-primary" %>
  </div>
</div>
<br>
<br>

app/views/pages/home.html.erb
<%= render 'banner' %>
<div class="container">
  <h1 class="latest-projects">Projects</h1>
    <%= form_tag root_path, method: :get, remote: true do %>
      <%= text_field_tag :query,
        params[:query],
        id: 'search',
        class: "form-control",
        placeholder: "Find a project"
      %>
    <% end %>

  <div class="row" id="results">
    <%= render "pages/results_home", results: @projects %>
  </div>
</div>
<script>
  const allProjects = []
</script>
<% @projects.each do |project| %>
  <script>allProjects.push(`<%= project.title %>`)</script>
<% end %>

<script>
  // const results = document.getElementById('results');

  // function refreshResults(results, innerHTML) {
  //   results.innerHTML = innerHTML;
  // }


  const displayCards = (word) => {

    document.querySelectorAll(".project-title").forEach((title) => {
      downcasedTitle = title.innerHTML.toLowerCase()
      downcasedWord = word.toLowerCase()
      if (downcasedTitle.includes(downcasedWord)) {
        title.parentNode.parentNode.parentNode.style.display = "block"
      } else {
        title.parentNode.parentNode.parentNode.style.display = "none";
      }
    })
    if (word === "") {
      document.querySelectorAll(".project-title").forEach((title) => {
        title.parentNode.parentNode.parentNode.style.display = "block"
      })
    }
  }

  const searchBar = document.getElementById('search');
  word = "";
  searchBar.addEventListener("keyup", (event) => {
    if (event.key == "Backspace") {
      word = word.substring(0, word.length - 1);
    } else if (event.key.length > 1 ) {
      console.log("not adding any letter")
    } else {
      word += event.key;
    }
    displayCards(word);
  })

</script>

<%= render 'how' %>
<%= render 'm' %>

app/views/pages/home.js.erb
const results = document.getElementById('results');

function refreshResults(results, innerHTML) {
  results.innerHTML = innerHTML;
}

const searchBar = document.getElementById('search')
searchBar.addEventListener("keyup", (event) => {
  console.log(event);
  refreshResults(results, '<%= j render "pages/results_home", results: @projects %>');
})