config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :views
  root to: 'pages#home'

  resources :users, only: [:show, :update] do
    resources :projects, only: [:index]
  end

  resources :projects do
    resources :contributions, only: [:new, :create]
  end

  resources :knowledges, only: [:new, :create, :destroy]

  get 'contributions/:id/remove_user', to: "contributions#remove_user", as: "remove_contribution_user"

  resources :contributions, only: [:edit, :update, :destroy, :show] do
    resources :requirements, only: [:new, :create]
    resources :interests, only: [:create]
  end

  resources :interests, only: [:destroy]

  resources :requirements, only: [:destroy]
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :contributions, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :github_url, allow_blank: true, format: { with: /(?:git|ssh|https?|git@[-\w.]+):(\/\/)?(.*?)(\.git)(\/?|\#[-\d\w._]+?)/, message: "Please enter valid GitHub url" }
  validates :user, presence: true

  def skills
    skills = []
    self.contributions.each do |contribution|
      contribution.skills.each { |skill| skills << skill }
    end
    skills.uniq
  end

  def interest?
    array = self.contributions.select { |contribution| contribution.interests.length > 0 && contribution.status == "open" }
    !array.empty?
  end

  include AlgoliaSearch

  algoliasearch do
    attribute :title, :description
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    if params[:query].present?
      @projects = Project.search(title: params[:query])
    else
      @projects = Project.all
    end
  end

  def show
    @project = Project.find(params[:id])
    authorize @project
    @skills = []
    @project.contributions.each do |contribution|
      contribution.skills.each { |skill| @skills << skill}
    end
    @skills.uniq
  end

  def edit
    @project = Project.find(params[:id])
    authorize @project
  end

  def update
    @project = Project.find(params[:id])
    authorize @project
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    authorize @project
    if @project.save
      Project.reindex
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def destroy
    @project = Project.find(params[:id])
    authorize @project
    @project.destroy
    redirect_to user_path(current_user)
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :guidelines, :github_url, :photo)
  end
end

app/views/projects/_new_form.html.erb
<%= simple_form_for @project do |f| %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.input :guidelines %>
<%= f.input :github_url %>
<%= f.submit %>
<% end %>

app/views/projects/_project_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <%= simple_form_for @project do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :guidelines %>
    <%= f.input :github_url %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Edit project</h1>
    </div>
  </div>
  <%= render 'project_form' %>
</div>

<!-- TO DO: check if simple form prepopulates form with exiting values or do it -->

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
    <% @projects.each do |project| %>
    <%= project.title %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Add a project</h1>
    </div>
  </div>
  <%= render 'project_form' %>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="project-show">

    <div class="header" id="last-section">
      <h1 class="text-center"><%= @project.title %></h1>
      <% unless @project.user == current_user %>
        <h3 class="text-center"><strong>Owner: </strong><%= link_to @project.user.full_name, user_path(@project.user) %></h3>
      <% end %>
    </div>

    <div class="skills-and-edit section">
      <div class="reqs-box">
        <p>Requirements: </p>
        <div class="reqs">
          <% @skills.uniq.each do |skill| %>
            <i class="devicon-center devicon-<%= skill.slug %>"></i>
          <% end %>
        </div>
      </div>
      <% if @project.user == current_user %>
        <h3 class="text-center"><%= link_to "edit", edit_project_path(@project) %></h3>
      <% end %>
    </div>

    <div class="description section">
      <h2>Description:</h2>
      <p><%= @project.description %></p>
    </div>

    <div class="guidlines section">
      <h2>Guidelines:</h2>
      <p><%= @project.guidelines %></p>
    </div>

    <h1 class="text-center">Contributions: <%= @project.contributions.length %> </h1>
    <% if @project.user == current_user %>
      <div class="text-center card-spacing"><%= link_to "Add contribution", new_project_contribution_path(@project)%></div>
    <% end %>

      <div class="row">
        <% @project.contributions.each do |contribution| %>
          <div class="col-xs-12 col-sm-4">
            <div class="thecard">
              <div class="card-caption">
                <div class="card-delete">
                  <% if contribution.status == "booked" %>
                    <p>booked</p>
                  <% elsif contribution.interests.length > 0 && contribution.status == "open" %>
                    <p>open with interest</p>
                  <% else %>
                    <p>open</p>
                  <% end %>
                  <% if contribution.user == current_user %>
                    <%= link_to remove_contribution_user_path(contribution) do %>
                      <p>unassign</p>
                    <% end %>
                  <% end %>
                </div>
                <i id="clock-btn" class="far fa-clock"></i>
                <span class="date">Last updated: <%= contribution.updated_at %></span>
                <h1 class="project-title"><%= contribution.title %></h1>
                <p class="card-description"><%= contribution.description[0, 100] %></p>
                <div class="reqs-box">
                  <p class ="card-skills"><strong><em>Relevant skills:</em> &ensp;</strong></p>
                  <div class="reqs">
                    <% contribution.skills.each do |skill| %>
                      <i class="devicon-<%= skill.slug %>"></i>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="card-out">
                <h5>Read more</h5>
                <i id="out-icon" class="fa fa-angle-right"></i>
              </div>
              <a class="card-link" href="<%= contribution_path(contribution) %>" ></a>
            </div>
          </div>
        <% end %>
      </div>



    <%= link_to "Back", :back %>
  </div>
</div>