config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :views
  root to: 'pages#home'

  resources :users, only: [:show, :update] do
    resources :projects, only: [:index]
  end

  resources :projects do
    resources :contributions, only: [:new, :create]
  end

  resources :knowledges, only: [:new, :create, :destroy]

  get 'contributions/:id/remove_user', to: "contributions#remove_user", as: "remove_contribution_user"

  resources :contributions, only: [:edit, :update, :destroy, :show] do
    resources :requirements, only: [:new, :create]
    resources :interests, only: [:create]
  end

  resources :interests, only: [:destroy]

  resources :requirements, only: [:destroy]
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :project
  belongs_to :user, optional: true
  has_many :requirements, dependent: :destroy
  has_many :skills, through: :requirements
  has_many :interests, dependent: :destroy

  validates :project, presence: true
  validates :description, presence: true
  validates :title, presence: true
  validates :status, presence: true, inclusion: { in: ["open", "booked", "closed"] }
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  def show
    @contribution = Contribution.find(params[:id])
    authorize @contribution
  end

  def new
    @project = Project.find(params[:project_id])
    @contribution = Contribution.new
    @contribution.project = @project
    authorize @contribution
  end

  def create
    @project = Project.find(params[:project_id])
    @contribution = Contribution.new(contribution_params)
    @contribution.project = @project
    authorize @contribution

    if @contribution.save
      redirect_to contribution_path(@contribution)
    else
      render :new
    end
  end

  def edit
    @contribution = Contribution.find(params[:id])
    authorize @contribution
  end

  def update
    @contribution = Contribution.find(params[:id])
    @contribution.status = "booked" unless @contribution.user.nil?
    authorize @contribution
    if @contribution.update(contribution_params)
      redirect_to contribution_path(@contribution)
    else
      render :edit
    end
  end

  def destroy
    @contribution = Contribution.find(params[:id])
    @contribution.destroy
  end

  def remove_user
    @contribution = Contribution.find(params[:id])
    @contribution.user = nil
    authorize @contribution
    if @contribution.save
      redirect_to user_path(current_user), notice: "Successful deletion"
    else
      redirect_to user_path(current_user), alert: "That didn't work"
    end
  end

  private

  def contribution_params
    params.require(:contribution).permit(:description, :title, :guidelines, :status, :user_id)
  end
end

app/views/contributions/_contribution_form.html.erb
  <%= simple_form_for [@project, @contribution] do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :guidelines %>
    <%= f.association :user, collection: User.all.reject { |user| user != @contribution.project.user && user.interests.select { |interest| interest.contribution == @contribution}.empty? }, label_method: :full_name %>

    <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/contributions/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Edit contribution</h1>
      <%= render 'contribution_form' %>
    </div>
  </div>
</div>

app/views/contributions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Add a contribution</h1>
      <%= render 'contribution_form' %>
    </div>
  </div>
</div>

app/views/contributions/show.html.erb
<div class="container">
  <div class="contribution-show">

    <div class="header" id="last-section">
      <h1 class="text-center"><%= @contribution.title %></h1>
      <h3 class="text-center"><strong>Project: </strong><%= link_to Project.find(@contribution.project_id).title, project_path(@contribution.project) %></h3>
      <h3>Interested users:</h3>
      <% @contribution.interests.each do |interest| %>
        <%= link_to interest.user.full_name, user_path(interest.user) %>
      <% end %>
    </div>

    <div class="skills-and-edit section">
      <div class="reqs-box">
        <p>Requirements: </p>
        <div class="reqs">
          <% @contribution.skills.each do |skill| %>
            <i class="devicon-center devicon-<%= skill.slug %>"></i>
          <% end %>
        </div>
        <% if @contribution.project.user == current_user %>
          <%= link_to "Add a skill", new_contribution_requirement_path(@contribution), class: "btn btn-primary" %>
        <% end %>
      </div>
      <% if @contribution.project.user == current_user %>
        <h3 class="text-center"><%= link_to "edit", edit_contribution_path(@contribution) %></h3>
      <% end %>
    </div>

    <div class="description section">
      <h2>Description:</h2>
      <p><%= @contribution.description %></p>
    </div>

    <div class="guidelines section">
      <h2>Guidelines:</h2>
      <p><%= @contribution.guidelines %></p>
    </div>

    <br>
    <h2>Status:</h2>
    <p><%= @contribution.status %></p>

    <% if @contribution.status == "booked" && !@contribution.user.nil? %>
      <h2>Assigned user:</h2>
      <p><%= link_to @contribution.user.full_name, user_path(@contribution.user) %></p>
    <% end %>

    <div class="interest-btns">
      <% if @contribution.project.user == current_user %>
        <%= link_to "Assign to user", edit_contribution_path(@contribution), class: "btn btn-primary" if @contribution.project.user == current_user %>
      <% else %>
        <%= link_to "Register interest", contribution_interests_path(@contribution), method: :post, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>